boot.o: boot.S multiboot.h x86_desc.h types.h
signal_assmbly.o: signal_assmbly.S signal_sys_call.h
x86_desc.o: x86_desc.S x86_desc.h types.h
file_sys.o: file_sys.c file_sys.h types.h multiboot.h lib.h terminal.h \
  rtc.h process.h x86_desc.h signal_sys_call.h idt.h link.h sys_call.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c multiboot.h types.h x86_desc.h lib.h file_sys.h link.h \
  process.h signal_sys_call.h idt.h sys_call.h page_lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h rtc.h terminal.h file_sys.h process.h signal_sys_call.h idt.h \
  link.h sys_call.h
lib.o: lib.c lib.h types.h
page_lib.o: page_lib.c page_lib.h x86_desc.h types.h file_sys.h \
  multiboot.h lib.h
paging.o: paging.c x86_desc.h types.h
process.o: process.c process.h file_sys.h types.h multiboot.h x86_desc.h \
  signal_sys_call.h idt.h link.h page_lib.h lib.h
rtc.o: rtc.c rtc.h types.h lib.h
signal_sys_call.o: signal_sys_call.c signal_sys_call.h idt.h types.h \
  link.h x86_desc.h process.h file_sys.h multiboot.h sys_call.h lib.h
sys_call.o: sys_call.c file_sys.h types.h multiboot.h process.h \
  x86_desc.h signal_sys_call.h idt.h link.h lib.h page_lib.h tests.h
terminal.o: terminal.c multiboot.h types.h x86_desc.h lib.h i8259.h \
  debug.h tests.h rtc.h terminal.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h rtc.h \
  file_sys.h multiboot.h process.h signal_sys_call.h idt.h link.h \
  sys_call.h
